services:
  dashboard:
    build: .
    ports:
      - "3000:3000"
    env_file: .env.example
    volumes:
      - ./public:/app/public
      - ./uploads:/app/uploads
    depends_on:
      - mqtt
      - mongo
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt
    ports:
      - "1883:1883"         # MQTT standard
      - "9001:9001"         # WebSocket (opzionale)
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
    restart: unless-stopped