name: Deploy bonsai-mqtt-dashboard

on:
  push:
    branches: [ master ]     # o main
    paths:
      - "app/**"
      - "mosquitto/**"
      - "data/**"
      - "compose.yaml"
      - ".github/workflows/deploy.yml"
      - "installer.sh"
      - "update.sh"
  workflow_dispatch: {}

concurrency:
  group: deploy-bonsai
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy installer/update scripts to Pi
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT || 22 }}
          source: "installer.sh,update.sh"
          target: "/tmp"
          # host_verification: false  # <-- solo se hai problemi con known_hosts

      - name: Run installer first time, update otherwise
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          port: ${{ secrets.PI_SSH_PORT || 22 }}
          # passphrase: ${{ secrets.PI_SSH_PASSPHRASE }}  # se la chiave ha passphrase
          # host_verification: false                      # opzionale
          script: |
            set -e
            if [ ! -d "/opt/bonsai-stack/app/.git" ]; then
              echo "➡️  Primo setup: installer.sh"
              sudo mkdir -p /opt/bonsai-stack
              sudo mv -f /tmp/installer.sh /opt/bonsai-stack/installer.sh
              sudo chmod +x /opt/bonsai-stack/installer.sh
              # override env opzionali:
              export STACK_DIR="/opt/bonsai-stack"
              export BRANCH="master"
              export PORT="3000"
              /opt/bonsai-stack/installer.sh
            else
              echo "➡️  Deploy: update.sh"
              sudo mv -f /tmp/update.sh /opt/bonsai-stack/update.sh
              sudo chmod +x /opt/bonsai-stack/update.sh
              /opt/bonsai-stack/update.sh
            fi
